### ISSUE TITLE
Fails on Mac

### ISSUE THREAD

**Issue by eliihen** [oslomarketsolutions/pre-commit-maven-plugin#1]
On mac it fails because python3 is not present:

```
[ERROR] Failed to execute goal no.oms.maven:pre-commit-maven-plugin:0.2.1:download-binary (default) on project norne: Failed to install binary: Python encountered an issue when installing the pre-commit binary: Exception when fetching python version from binary: Cannot run program "python3": error=2, No such file or directory -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal no.oms.maven:pre-commit-maven-plugin:0.2.1:download-binary (default) on project norne: Failed to install binary
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to install binary
	at no.oms.maven.precommit.mojo.DownloadBinaryMojo.execute(DownloadBinaryMojo.java:45)
	at no.oms.maven.precommit.mojo.AbstractPrecommitMojo.execute(AbstractPrecommitMojo.java:45)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: no.oms.maven.precommit.lib.InstallationException: Python encountered an issue when installing the pre-commit binary
	at no.oms.maven.precommit.lib.BinaryInstaller.installBinary(BinaryInstaller.java:70)
	at no.oms.maven.precommit.mojo.DownloadBinaryMojo.execute(DownloadBinaryMojo.java:43)
	... 23 more
Caused by: no.oms.maven.precommit.lib.PythonException: Exception when fetching python version from binary:
	at no.oms.maven.precommit.lib.DefaultPythonHandle.getPython3Executable(PythonHandle.java:185)
	at no.oms.maven.precommit.lib.DefaultPythonHandle.setupVirtualEnv(PythonHandle.java:50)
	at no.oms.maven.precommit.lib.BinaryInstaller.installBinary(BinaryInstaller.java:59)
	... 24 more
Caused by: java.io.IOException: Cannot run program "python3": error=2, No such file or directory
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at java.lang.Runtime.exec(Runtime.java:485)
	at no.oms.maven.precommit.lib.DefaultPythonHandle.getPython3Executable(PythonHandle.java:171)
	... 26 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 29 more
```

**Comment by eliihen** [comment]
Fixed in e663530c4247571df3278b660b98511b689ac3de
