### ISSUE TITLE
pyyaml missing on mac

### ISSUE THREAD

**Issue by eliihen** [oslomarketsolutions/pre-commit-maven-plugin#2]
Throws on initialize. Seems to fail at compiling pyyaml due to pulling 4.2 beta instad of 3.13 which is stable. This only happens on some machines for some reasons, some machines (like mine) resolve the dependency to pyyaml correctly to version 3.13 when running setuptools' `setup.py install`.

The "easy fix" would be to install pyyaml into the vitualenv before running `setup.py` on pre-commit.

Workaround: Activate the virtualenv with `source precommit_files/pre-commit/.pre-commit-virtualenv/bin/activate` and run `pip install pyyaml`

```
[DEBUG] Searching for pyyaml
[DEBUG] Reading https://pypi.python.org/simple/pyyaml/
[DEBUG] Downloading https://files.pythonhosted.org/packages/a8/c6/a8d1555e795dbd0375c3c93b576ca13bbf139db51ea604afa19a2c35fc03/PyYAML-4.2b4.tar.gz#sha256=3c17fb92c8ba2f525e4b5f7941d850e7a48c3a59b32d331e2502a3cdc6648e76
[DEBUG] Best match: PyYAML 4.2b4
[DEBUG] Processing PyYAML-4.2b4.tar.gz
[DEBUG] Writing /tmp/easy_install-2a46a6aw/PyYAML-4.2b4/setup.cfg
[DEBUG] Running PyYAML-4.2b4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-2a46a6aw/PyYAML-4.2b4/egg-dist-tmp-jkdfh7dv
[ERROR] Traceback (most recent call last):
[ERROR]   File "/Users/kristha/Projects/norne/precommit_files/pre-commit/.pre-commit-virtualenv/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
[ERROR]     yield saved
[ERROR]   File "/Users/kristha/Projects/norne/precommit_files/pre-commit/.pre-commit-virtualenv/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
[ERROR]     yield
[ERROR]   File "/Users/kristha/Projects/norne/precommit_files/pre-commit/.pre-commit-virtualenv/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
[ERROR]     _execfile(setup_script, ns)
[ERROR]   File "/Users/kristha/Projects/norne/precommit_files/pre-commit/.pre-commit-virtualenv/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
[ERROR]     exec(code, globals, locals)
[ERROR]   File "/tmp/easy_install-2a46a6aw/PyYAML-4.2b4/setup.py", line 302, in <module>
[ERROR]   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
[ERROR]     dist.run_commands()
[ERROR]   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
[ERROR]     self.run_command(cmd)
[ERROR]   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
[ERROR]     cmd_obj.run()
[ERROR]   File "/Users/kristha/Projects/norne/precommit_files/pre-commit/.pre-commit-virtualenv/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 172, in run
[ERROR]     cmd = self.call_command('install_lib', warn_dir=0)
[ERROR]   File "/Users/kristha/Projects/norne/precommit_files/pre-commit/.pre-commit-virtualenv/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
[ERROR]     self.run_command(cmdname)
[ERROR]   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
[ERROR]     self.distribution.run_command(command)
[ERROR]   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
[ERROR]     cmd_obj.run()
[ERROR]   File "/Users/kristha/Projects/norne/precommit_files/pre-commit/.pre-commit-virtualenv/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
[ERROR]     self.build()
[ERROR]   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/install_lib.py", line 107, in build
[ERROR]     self.run_command('build_ext')
[ERROR]   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
[ERROR]     self.distribution.run_command(command)
[ERROR]   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
[ERROR]     cmd_obj.run()
[ERROR]   File "/tmp/easy_install-2a46a6aw/PyYAML-4.2b4/setup.py", line 173, in run
[ERROR]   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build_ext.py", line 309, in run
[ERROR]     customize_compiler(self.compiler)
[ERROR]   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/sysconfig.py", line 170, in customize_compiler
[ERROR]     _osx_support.customize_compiler(_config_vars)
[ERROR]   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_osx_support.py", line 418, in customize_compiler
[ERROR]     _find_appropriate_compiler(_config_vars)
[ERROR]   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_osx_support.py", line 167, in _find_appropriate_compiler
[ERROR]     if not _find_executable(cc):
[ERROR]   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_osx_support.py", line 36, in _find_executable
[ERROR]     path = os.environ['PATH']
[ERROR]   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py", line 678, in __getitem__
[ERROR]     raise KeyError(key) from None
[ERROR] KeyError: 'PATH'
[ERROR]
[ERROR] During handling of the above exception, another exception occurred:
[ERROR]
[ERROR] Traceback (most recent call last):
[ERROR]   File "/Users/kristha/Projects/norne/precommit_files/pre-commit/setup.py", line 53, in <module>
[ERROR]     'pre-commit-validate-manifest = pre_commit.clientlib:validate_manifest_main',  # noqa
[ERROR]   File "/Users/kristha/Projects/norne/precommit_files/pre-commit/.pre-commit-virtualenv/lib/python3.7/site-packages/setuptools/__init__.py", line 129, in setup
[ERROR]     return distutils.core.setup(**attrs)
[ERROR]   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
[ERROR]     dist.run_commands()
[ERROR]   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
[ERROR]     self.run_command(cmd)
[ERROR]   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
[ERROR]     cmd_obj.run()
[ERROR]   File "/Users/kristha/Projects/norne/precommit_files/pre-commit/.pre-commit-virtualenv/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
[ERROR]     self.do_egg_install()
[ERROR]   File "/Users/kristha/Projects/norne/precommit_files/pre-commit/.pre-commit-virtualenv/lib/python3.7/site-packages/setuptools/command/install.py", line 117, in do_egg_install
[ERROR]     cmd.run()
[ERROR]   File "/Users/kristha/Projects/norne/precommit_files/pre-commit/.pre-commit-virtualenv/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 412, in run
[ERROR]     self.easy_install(spec, not self.no_deps)
[ERROR]   File "/Users/kristha/Projects/norne/precommit_files/pre-commit/.pre-commit-virtualenv/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 654, in easy_install
[ERROR]     return self.install_item(None, spec, tmpdir, deps, True)
[ERROR]   File "/Users/kristha/Projects/norne/precommit_files/pre-commit/.pre-commit-virtualenv/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 701, in install_item
[ERROR]     self.process_distribution(spec, dist, deps)
[ERROR]   File "/Users/kristha/Projects/norne/precommit_files/pre-commit/.pre-commit-virtualenv/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 746, in process_distribution
[ERROR]     [requirement], self.local_index, self.easy_install
[ERROR]   File "/Users/kristha/Projects/norne/precommit_files/pre-commit/.pre-commit-virtualenv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 774, in resolve
[ERROR]     replace_conflicting=replace_conflicting
[ERROR]   File "/Users/kristha/Projects/norne/precommit_files/pre-commit/.pre-commit-virtualenv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1057, in best_match
[ERROR]     return self.obtain(req, installer)
[ERROR]   File "/Users/kristha/Projects/norne/precommit_files/pre-commit/.pre-commit-virtualenv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1069, in obtain
[ERROR]     return installer(requirement)
[ERROR]   File "/Users/kristha/Projects/norne/precommit_files/pre-commit/.pre-commit-virtualenv/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 673, in easy_install
[ERROR]     return self.install_item(spec, dist.location, tmpdir, deps)
[ERROR]   File "/Users/kristha/Projects/norne/precommit_files/pre-commit/.pre-commit-virtualenv/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 699, in install_item
[ERROR]     dists = self.install_eggs(spec, download, tmpdir)
[ERROR]   File "/Users/kristha/Projects/norne/precommit_files/pre-commit/.pre-commit-virtualenv/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 884, in install_eggs
[ERROR]     return self.build_and_install(setup_script, setup_base)
[ERROR]   File "/Users/kristha/Projects/norne/precommit_files/pre-commit/.pre-commit-virtualenv/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1152, in build_and_install
[ERROR]     self.run_setup(setup_script, setup_base, args)
[ERROR]   File "/Users/kristha/Projects/norne/precommit_files/pre-commit/.pre-commit-virtualenv/lib/python3.7/site-packages/setuptools/command/easy_install.py", line 1138, in run_setup
[ERROR]     run_setup(setup_script, args)
[ERROR]   File "/Users/kristha/Projects/norne/precommit_files/pre-commit/.pre-commit-virtualenv/lib/python3.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
[ERROR]     raise
[ERROR]   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__
[ERROR]     self.gen.throw(type, value, traceback)
[ERROR]   File "/Users/kristha/Projects/norne/precommit_files/pre-commit/.pre-commit-virtualenv/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
[ERROR]     yield
[ERROR]   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__
[ERROR]     self.gen.throw(type, value, traceback)
[ERROR]   File "/Users/kristha/Projects/norne/precommit_files/pre-commit/.pre-commit-virtualenv/lib/python3.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
[ERROR]     saved_exc.resume()
[ERROR]   File "/Users/kristha/Projects/norne/precommit_files/pre-commit/.pre-commit-virtualenv/lib/python3.7/site-packages/setuptools/sandbox.py", line 141, in resume
[ERROR]     six.reraise(type, exc, self._tb)
[ERROR]   File "/Users/kristha/Projects/norne/precommit_files/pre-commit/.pre-commit-virtualenv/lib/python3.7/site-packages/setuptools/_vendor/six.py", line 685, in reraise
[ERROR]     raise value.with_traceback(tb)
[ERROR]   File "/Users/kristha/Projects/norne/precommit_files/pre-commit/.pre-commit-virtualenv/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
[ERROR]     yield saved
[ERROR]   File "/Users/kristha/Projects/norne/precommit_files/pre-commit/.pre-commit-virtualenv/lib/python3.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
[ERROR]     yield
[ERROR]   File "/Users/kristha/Projects/norne/precommit_files/pre-commit/.pre-commit-virtualenv/lib/python3.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
[ERROR]     _execfile(setup_script, ns)
[ERROR]   File "/Users/kristha/Projects/norne/precommit_files/pre-commit/.pre-commit-virtualenv/lib/python3.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
[ERROR]     exec(code, globals, locals)
[ERROR]   File "/tmp/easy_install-2a46a6aw/PyYAML-4.2b4/setup.py", line 302, in <module>
[ERROR]   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
[ERROR]     dist.run_commands()
[ERROR]   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
[ERROR]     self.run_command(cmd)
[ERROR]   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
[ERROR]     cmd_obj.run()
[ERROR]   File "/Users/kristha/Projects/norne/precommit_files/pre-commit/.pre-commit-virtualenv/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 172, in run
[ERROR]     cmd = self.call_command('install_lib', warn_dir=0)
[ERROR]   File "/Users/kristha/Projects/norne/precommit_files/pre-commit/.pre-commit-virtualenv/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 158, in call_command
[ERROR]     self.run_command(cmdname)
[ERROR]   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
[ERROR]     self.distribution.run_command(command)
[ERROR]   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
[ERROR]     cmd_obj.run()
[ERROR]   File "/Users/kristha/Projects/norne/precommit_files/pre-commit/.pre-commit-virtualenv/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
[ERROR]     self.build()
[ERROR]   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/install_lib.py", line 107, in build
[ERROR]     self.run_command('build_ext')
[ERROR]   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
[ERROR]     self.distribution.run_command(command)
[ERROR]   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
[ERROR]     cmd_obj.run()
[ERROR]   File "/tmp/easy_install-2a46a6aw/PyYAML-4.2b4/setup.py", line 173, in run
[ERROR]   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build_ext.py", line 309, in run
[ERROR]     customize_compiler(self.compiler)
[ERROR]   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/sysconfig.py", line 170, in customize_compiler
[ERROR]     _osx_support.customize_compiler(_config_vars)
[ERROR]   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_osx_support.py", line 418, in customize_compiler
[ERROR]     _find_appropriate_compiler(_config_vars)
[ERROR]   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_osx_support.py", line 167, in _find_appropriate_compiler
[ERROR]     if not _find_executable(cc):
[ERROR]   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_osx_support.py", line 36, in _find_executable
[ERROR]     path = os.environ['PATH']
[ERROR]   File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/os.py", line 678, in __getitem__
[ERROR]     raise KeyError(key) from None
[ERROR] KeyError: 'PATH'
```

**Comment by eliihen** [comment]
Fixed in 0.2.3
